### ISSUE TITLE
Twitter/X parse error

### ISSUE THREAD

**Issue by mazzzystar** [jina-ai/reader#145]
```
https://r.jina.ai/https://twitter.com/USTechWorkers/status/1843744799607898260
```

I got:
```
Title: X

URL Source: https://twitter.com/USTechWorkers/status/1843744799607898260

Markdown Content:
Don’t miss what’s happening

People on X are the first to know.
```

**Comment by nomagick** [comment]
This should be X changing its implementation a little bit and providing some preview content.
By default, Reader eagerly tries to return ASAP, this has resulted in Reader returning the preview content instead of the full content, which is made available after.

To walk around this, you may pass `X-Timeout: 30` header to explicitly set a deadline. This changes the return policy and makes Reader wait more patiently until deadline or [`networkidle0`](https://github.com/puppeteer/puppeteer/blob/8bd699931cbebc5397c26a023d3fe6a110192173/docs/api/puppeteer.puppeteerlifecycleevent.md?plain=1#L23)

**Comment by mazzzystar** [comment]
Thx : )
