### ISSUE TITLE
Timeout for both twitter and reddit happening frequently

### ISSUE THREAD

**Issue by kleenkanteen** [jina-ai/reader#29]
Around 50% of the time, this tweet and the few others I tried shows a timeout error: [https://r.jina.ai/https://twitter.com/EntreEden/status/1780771887624417315](https://r.jina.ai/https://twitter.com/EntreEden/status/1780771887624417315).

The response I get is this:
```
{"name":"TimeoutError",
"domainThrown":true,
"message":"Timed out after 10000 ms while waiting for the WS endpoint URL to appear in stdout!"}
```

Same with a reddit post I tried: [https://www.reddit.com/r/cscareerquestions/comments/ufdyhd/after_4_years_of_working_im_slowly_learning_how/](https://www.reddit.com/r/cscareerquestions/comments/ufdyhd/after_4_years_of_working_im_slowly_learning_how/)

I am in Canada, all on my home wifi and computer.

If you need help with scaling, I have a $5 Hetzner vps that I can pitch in. If I get guidance, I'm willing to help out with the issue as well.

**Comment by hanxiao** [comment]
yeah, recently some instances were somehow broken, so the user will have some chance to hit the bad instances and we have fixed that few hours ago.

Reddit issue is rather complicated, there is some room improvement on our side, trying to fix it.

**Comment by kleenkanteen** [comment]
I thought this project used firebase functions, so what do you mean by some instances?

And are you trying to identify what the source of the timeout is?

**Comment by hanxiao** [comment]
yes, it is firebase function, but this doesn't mean there is no instance running behind. in fact, you can control the scaling config to set up the number of instances and number of concurrent functions in one instances. https://firebase.google.com/docs/functions/manage-functions?gen=2nd#min-max-instances

the reason was some instance running into a bad status and heath check can't detect them and hence can't restart them. We rolled out a fix two days ago and this issue should be fixed.

**Comment by kleenkanteen** [comment]
I did the same level of usage today with the same tweets. No issues.
